networks:
  trainer-journal-dev:
    driver: bridge

services:
  trainer-journal.api:
    container_name: trainer-journal.api
    image: trainer-journal.api
    build:
      context: .
      dockerfile: src/TrainerJournal.API/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONTAINER: "trainer-journal.db"
    depends_on:
      - trainer-journal.db
      - minio
      
  trainer-journal.db:
    container_name: trainer-journal.db
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web
    environment:
      - MINIO_ROOT_USER=${STORAGE_USER}
      - MINIO_ROOT_PASSWORD=${STORAGE_PASSWORD}
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
  minio-data:
    driver: local
  minio-config:
    driver: local