networks:
  trainer-journal-dev:
    driver: bridge

services:
  trainer-journal.api:
    container_name: trainer-journal.api
    image: trainer-journal.api
    build:
      context: .
      dockerfile: src/TrainerJournal.API/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONTAINER: "trainer-journal.db"
      
  trainer-journal.db:
    container_name: trainer-journal.db
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    depends_on:
      - trainer-journal.api

volumes:
  postgres-data: